-- ════════════════════════════════════════
-- V1: Initial Schema - Hospital Queue System
-- ════════════════════════════════════════

CREATE TABLE IF NOT EXISTS departments (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL UNIQUE,
    code        VARCHAR(20)  NOT NULL UNIQUE,
    description VARCHAR(500),
    max_queue   INT          NOT NULL DEFAULT 50,
    active      BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(80)  NOT NULL UNIQUE,
    email         VARCHAR(150) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    full_name     VARCHAR(150) NOT NULL,
    phone         VARCHAR(20),
    role          VARCHAR(30)  NOT NULL,
    enabled       BOOLEAN      NOT NULL DEFAULT TRUE,
    locked        BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS doctors (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT       NOT NULL UNIQUE,
    department_id   BIGINT       NOT NULL,
    specialization  VARCHAR(150) NOT NULL,
    license_number  VARCHAR(50)  NOT NULL UNIQUE,
    status          VARCHAR(30)  NOT NULL DEFAULT 'AVAILABLE',
    consultation_duration_min INT NOT NULL DEFAULT 15,
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_doctor_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_doctor_dept FOREIGN KEY (department_id) REFERENCES departments(id)
);

CREATE TABLE IF NOT EXISTS patients (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_number VARCHAR(20)  NOT NULL UNIQUE,
    full_name      VARCHAR(150) NOT NULL,
    email          VARCHAR(150),
    phone          VARCHAR(20)  NOT NULL,
    date_of_birth  DATE,
    gender         VARCHAR(10),
    blood_type     VARCHAR(5),
    address        VARCHAR(300),
    allergies      VARCHAR(500),
    emergency_contact_name  VARCHAR(150),
    emergency_contact_phone VARCHAR(20),
    created_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS queue_entries (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_number   VARCHAR(20)  NOT NULL UNIQUE,
    patient_id      BIGINT       NOT NULL,
    doctor_id       BIGINT,
    department_id   BIGINT       NOT NULL,
    priority        VARCHAR(20)  NOT NULL DEFAULT 'NORMAL',
    status          VARCHAR(30)  NOT NULL DEFAULT 'WAITING',
    chief_complaint VARCHAR(500),
    notes           VARCHAR(1000),
    vitals          VARCHAR(500),
    registered_by   BIGINT       NOT NULL,
    registered_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    called_at       TIMESTAMP,
    seen_at         TIMESTAMP,
    completed_at    TIMESTAMP,
    estimated_wait_min INT,
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_queue_patient  FOREIGN KEY (patient_id)    REFERENCES patients(id),
    CONSTRAINT fk_queue_doctor   FOREIGN KEY (doctor_id)     REFERENCES doctors(id),
    CONSTRAINT fk_queue_dept     FOREIGN KEY (department_id) REFERENCES departments(id),
    CONSTRAINT fk_queue_regby    FOREIGN KEY (registered_by) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS chat_messages (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id     VARCHAR(100) NOT NULL,
    sender_id   BIGINT       NOT NULL,
    sender_name VARCHAR(150) NOT NULL,
    content     VARCHAR(2000) NOT NULL,
    message_type VARCHAR(20) NOT NULL DEFAULT 'TEXT',
    sent_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_chat_sender FOREIGN KEY (sender_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS audit_logs (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT,
    username     VARCHAR(80)  NOT NULL,
    action       VARCHAR(100) NOT NULL,
    entity_type  VARCHAR(80),
    entity_id    VARCHAR(50),
    old_value    VARCHAR(2000),
    new_value    VARCHAR(2000),
    ip_address   VARCHAR(45),
    user_agent   VARCHAR(500),
    status       VARCHAR(20)  NOT NULL DEFAULT 'SUCCESS',
    error_message VARCHAR(500),
    performed_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_queue_status      ON queue_entries(status);
CREATE INDEX IF NOT EXISTS idx_queue_dept        ON queue_entries(department_id);
CREATE INDEX IF NOT EXISTS idx_queue_doctor      ON queue_entries(doctor_id);
CREATE INDEX IF NOT EXISTS idx_queue_created     ON queue_entries(created_at);
CREATE INDEX IF NOT EXISTS idx_audit_username    ON audit_logs(username);
CREATE INDEX IF NOT EXISTS idx_audit_performed   ON audit_logs(performed_at);
CREATE INDEX IF NOT EXISTS idx_chat_room         ON chat_messages(room_id);
CREATE INDEX IF NOT EXISTS idx_patient_number    ON patients(patient_number);
CREATE INDEX IF NOT EXISTS idx_users_email       ON users(email);
